name: stacked_localisation_generator
description: a package that generates string keys for use with the the localisation service in a type safe manner
version: 0.1.0+1
homepage: https://github.com/FilledStacks/stacked/tree/master/packages/stacked_localisation/stacked_localisation_generator

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^2.3.0
  source_gen: ^1.2.2
  analyzer: ^4.1.0
  mustache: ^1.1.1
  glob: ^2.0.0
  path: ^1.6.4
  yaml: ^3.0.0

dev_dependencies:
  test:
  build_runner:
  build_test:
