name: stacked_generator
description: Stacked Generator is a package dedicated to reduce the boilerplate required to setup a stacked application
version: 0.5.7
homepage: https://github.com/FilledStacks/stacked/tree/master/packages/stacked_generator
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  build: ^2.2.1
  source_gen: ^1.2.1
  analyzer: ^3.1.0
  path: ^1.8.0
  # logger: ^1.0.0
  recase: ^4.0.0
  stacked:
    # git: 
    #   url: https://github.com/vincentderidder/stacked.git
    #   path: packages/stacked
    # ^2.2.2
     path: ../stacked

dev_dependencies:
  build_runner: ^2.0.6
  source_gen_test: ^1.0.0
  test:
